{
    'name': 'Sistema de Gestión de Ventas y Viajes',
    'version': '1.0.0',
    'summary': 'Gestión de ventas, viajes, productos y deudas',
    'category': 'Sales',
    'author': 'Tu Empresa',
    'website': 'https://www.tuempresa.com',
    'license': 'LGPL-3',
    'depends': ['base','mail'],
    'data': [
        'security/ir.model.access.csv',
        'views/persona_views.xml',
        'views/producto_views.xml',
        'views/viaje_views.xml',
        'views/venta_views.xml',
        'views/deuda_views.xml',
        'views/pago_deuda_views.xml',
        'views/menu.xml',
    ],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}